# Generated by Django 5.2.4 on 2025-12-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('necklace', 'Necklace'), ('bangle', 'Bangle'), ('earings', 'Earings'), ('ring', 'Ring')], default='necklace', max_length=20),
        ),
    ]
