# Generated by Django 5.2.4 on 2025-12-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
