# Generated by Django 5.2.4 on 2025-12-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_receipt',
            field=models.ImageField(blank=True, help_text='Upload GCash payment receipt (required for GCash orders)', null=True, upload_to='gcash_receipts/'),
        ),
    ]
