# Generated by Django 5.0.6 on 2025-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
