# Generated by Django 5.0.6 on 2025-08-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_product_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product_sold',
            new_name='products_sold',
        ),
    ]
