# Generated by Django 5.2.4 on 2025-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('necklace', 'Necklace'), ('bangle', 'Bangle'), ('earring', 'Earring')], default='necklace', max_length=20),
        ),
    ]
